votingworks/vxpollbook

backend/src/app.ts
backend/src/backup_worker.ts
backend/src/store.ts
backend/src/types.ts
backend/src/voter_checklist.tsx
frontend/src/api.ts
frontend/src/voter_search_screen.tsx
libs/ui/src/index.ts

#12 
Adds machine and global check in counters to the voter search screen and the voter checklist PDF.

Check in counters

---

backend/src/types.ts
backend/src/voter_checklist.tsx
frontend/src/us_states.ts
frontend/src/voter_confirm_screen.tsx

Merge out-of-state driver's license with regular driver's license.

Consolidate to a single photo ID identification method

---

backend/src/app.ts
backend/src/types.ts
frontend/package.json
frontend/src/api.ts
frontend/src/nav_screen.tsx
frontend/src/poll_worker_screen.tsx
libs/ui/package.json
libs/ui/src/battery_display.tsx
libs/ui/src/icons.tsx
libs/ui/src/left_nav.tsx
pnpm-lock.yaml

#19 
Adds a device status bar to the top of all screens that shows basic status for the printer, usb drive, battery, and mesh network (number of connected pollbooks).

Device status indicators

---

backend/schema.sql
backend/src/app.ts
backend/src/check_in_receipt.tsx
backend/src/receipt_helpers.tsx
backend/src/registration_receipt.tsx
backend/src/store.ts
backend/src/store_multi_node.test.ts
backend/src/test_helpers.ts
backend/src/types.ts
backend/src/voter_checklist.tsx
frontend/src/add_voter_screen.tsx
frontend/src/api.ts
frontend/src/election_manager_screen.tsx
frontend/src/nav_screen.tsx
frontend/src/poll_worker_screen.tsx
frontend/src/voter_confirm_screen.tsx
frontend/src/voter_search_screen.tsx
libs/ui/src/icons.tsx
libs/ui/src/segmented_button.tsx

Task: #8 
Adds an absentee mode toggle for election managers. When in absentee mode:
- The poll worker voter check-in flow has an "Absentee Mode" callout
- All check-ins are recorded with an `isAbsentee` flag
- The check-in receipt reads "Absentee" 
- The backup checklist has "A.V." in the first column for checked-in voters
https://github.com/user-attachments/assets/85c588dc-58be-490a-a121-c77aa2073f05

Absentee Mode

---

frontend/src/voter_search_screen.tsx

Show absentee check-in status in voter search

---

backend/src/backup_worker.ts

Fixes #58 
Instead of keeping two local copies (previous and latest), keep one local copy (latest). When writing to the USB drive, write to a temporary "in-progress" backup PDF on the drive, then move this to the main filename (backup_voter_checklist.pdf). This ensures that backup_voter_checklist.pdf is always present on the USB drive.
https://github.com/user-attachments/assets/00cd372a-d85b-445b-9bee-c66366ed3d9b

Improve resilience when backing up checklist to USB drive

---

backend/src/store.ts

Closes https://github.com/votingworks/vxpollbook/issues/83

Increase max voter search results to 100

---

backend/src/address_change_receipt.tsx
backend/src/app.ts
backend/src/event_helpers.ts
backend/src/registration_receipt.tsx
backend/src/store.ts
backend/src/test_helpers.ts
backend/src/types.ts
frontend/src/add_voter_screen.tsx
frontend/src/address_input_group.tsx
frontend/src/api.ts
frontend/src/election_info_bar.tsx
frontend/src/poll_worker_screen.tsx
frontend/src/shared_components.tsx
frontend/src/update_address_flow.tsx
frontend/src/voter_confirm_screen.tsx
frontend/src/voter_search_screen.tsx

Closes: #22 
https://github.com/user-attachments/assets/08705f8b-8eff-4052-a3b0-189a5d5b0967

Address change flow

---

frontend/src/voter_search_screen.tsx

Show updated address in voter search

---

backend/src/registration_receipt.tsx
frontend/src/add_voter_screen.tsx

NH is particular about this distinction, should be "Undeclared."

undecided -> undeclared

---

backend/src/registration_receipt.tsx
frontend/src/add_voter_screen.tsx
frontend/src/nav_screen.tsx
frontend/src/poll_worker_screen.tsx

Change "register" copy to "add voter"

---

frontend/src/add_voter_screen.tsx
frontend/src/nav_screen.tsx

revert headers on registration

---

frontend/src/nav_screen.tsx
libs/utils/src/format.ts

Show current date and time in device info bar

---

backend/src/check_in_receipt.tsx

Add recognizer initals to check-in receipt

---

frontend/src/election_manager_screen.tsx
libs/ui/src/segmented_button.tsx

Stats screen design polish

---

script/run-vxpollbook.desktop
script/update-vxpollbook.sh

Small tweaks and bug fix for vxdev setup

Vxdev improvements

---

backend/src/address_change_receipt.tsx
frontend/src/election_manager_screen.tsx
frontend/src/shared_components.tsx
frontend/src/unconfigured_screen.tsx
frontend/src/update_address_flow.tsx

Assorted UI polish

---

frontend/src/election_manager_screen.tsx

Fixes https://github.com/votingworks/vxpollbook/issues/149

Fix throughput chart padding

---

backend/src/pollbook_package.ts

Add missing leading zeros to zip codes on configuration

---

backend/src/app.ts
backend/src/receipts/address_change_receipt.tsx
backend/src/receipts/check_in_receipt.tsx
backend/src/receipts/index.tsx
backend/src/receipts/printing.ts
backend/src/receipts/receipt_helpers.tsx
backend/src/receipts/registration_receipt.tsx
backend/src/receipts/undo_check_in_receipt.tsx

Closes #146, closes #148 
Also adds voter's party to all receipts

Print receipt for undo check-in

---

backend/src/receipts/check_in_receipt.tsx
backend/src/receipts/receipt_helpers.tsx
backend/src/receipts/undo_check_in_receipt.tsx

Accidentally merged #153 before adding these changes

Add missing changes from undo check-in receipt

---

backend/src/app.ts
backend/src/event_helpers.ts
backend/src/receipts/undo_check_in_receipt.tsx
backend/src/store.ts
backend/src/types.ts
frontend/src/election_manager_screen.tsx
frontend/src/statistics_screen.tsx
frontend/src/voters_screen.tsx

Closes #147, closes #9 
https://github.com/user-attachments/assets/b366352a-8637-4dd7-bbe4-6404d98257d0

Record reason for undoing voter check-in

---

backend/src/app.ts
backend/src/event_helpers.ts
backend/src/receipts/index.tsx
backend/src/receipts/name_change_receipt.tsx
backend/src/receipts/receipt_helpers.tsx
backend/src/store.ts
backend/src/types.ts
backend/src/voter_checklist.tsx
frontend/src/add_voter_screen.tsx
frontend/src/api.ts
frontend/src/name_input_group.tsx
frontend/src/shared_components.tsx
frontend/src/update_name_flow.tsx
frontend/src/voter_confirm_screen.tsx
frontend/src/voter_search_screen.tsx

Closes #23 
Adds a flow for a poll worker to update a voter's name (mimicking the address change flow).
https://github.com/user-attachments/assets/a40eec9f-8ceb-4c5d-8104-ba263a944eb7

Name change flow

---

backend/src/receipts/check_in_receipt.tsx
backend/src/receipts/receipt_helpers.tsx
backend/src/receipts/undo_check_in_receipt.tsx
backend/src/test_helpers.ts
backend/src/types.ts
backend/src/voter_checklist.tsx
frontend/src/us_states.ts
frontend/src/voter_confirm_screen.tsx
frontend/src/voter_search_screen.tsx

- Update the check-in flow to use a single checkbox for OOSDL
- Update voter search results to only show identification method details for OOSDL
- Update receipts similarly

Change identification methods to default/out-of-state license

---

backend/package.json
backend/scripts/simulate_check_ins.ts
backend/src/app.ts
backend/src/store.ts
frontend/src/api.ts
frontend/src/election_manager_screen.tsx
frontend/src/export_voter_activity.tsx
frontend/src/nav_screen.tsx
frontend/src/voters_screen.tsx
pnpm-lock.yaml

Closes #80 
Adds a button to the election manager Voters screen to export a CSV of voter activity to the usb drive. Also groups the Election and Settings screen into a single Settings screen to simplify the EM UI.
[voter_activity_dev_2025-02-24_14-52-34.csv](https://github.com/user-attachments/files/18950992/voter_activity_dev_2025-02-24_14-52-34.csv)
https://github.com/user-attachments/assets/6e82d4be-ec6d-4400-8e35-b2d31dc1ee33

Voter activity export

---

backend/src/app.ts
frontend/src/poll_worker_screen.tsx

Closes https://github.com/votingworks/vxpollbook/issues/187

Show message if voter already checked in after confirm

---

backend/src/voter_checklist.tsx
frontend/src/add_voter_screen.tsx

Show full mailing address in backup voter checklist

---

backend/src/backup_worker.ts
backend/src/voter_checklist.tsx

Add certification page to end of backup voter checklist

---

frontend/src/add_voter_screen.tsx
frontend/src/address_input_group.tsx

Parse street number suffix correctly on address change

---

frontend/src/voters_screen.tsx

Closes #205 
https://github.com/user-attachments/assets/199a397f-44fc-4412-ac16-06769019fafc

Block undo check-in if printer disconnected

---

backend/src/backup_worker.ts

Closes #196 
Splits the voter checklist PDF pages up into chunks based on the number of voters in each letter group (which is a good proxy for the number of pages). h/t @carolinemodic for the idea

Balance voter checklist PDF page counts

---

backend/src/pollbook_package.ts

Convert Zip 5 -> Postal Zip 5 and Mailing Town -> Mailing City/Town

Support new voters.csv column headers

---

backend/src/store.ts
frontend/src/poll_worker_screen.tsx
frontend/src/voter_search_screen.tsx
frontend/src/voters_screen.tsx
pnpm-lock.yaml

Closes: https://github.com/votingworks/vxpollbook/issues/197
Closes: https://github.com/votingworks/vxpollbook/issues/198
Closes: https://github.com/votingworks/vxpollbook/issues/206

Check-in flow polish

---

backend/src/app.ts
backend/src/receipts/receipt_helpers.tsx
backend/src/voter_checklist.tsx
frontend/src/shared_components.tsx

Closes https://github.com/votingworks/vxpollbook/issues/203

Don't show 4-digit zip code suffix

---

backend/src/receipts/address_change_receipt.tsx
backend/src/receipts/check_in_receipt.tsx
backend/src/receipts/name_change_receipt.tsx
backend/src/receipts/receipt_helpers.tsx
backend/src/receipts/registration_receipt.tsx
backend/src/receipts/undo_check_in_receipt.tsx

Closes https://github.com/votingworks/vxpollbook/issues/204
Closes https://github.com/votingworks/vxpollbook/issues/201

Receipt polish

---

backend/src/voter_checklist.tsx
frontend/src/shared_components.tsx

Always put suffix at end of voter name, even when showing last name first

---

backend/src/backup_worker.ts

Forgot to commit this change in #234

Fix typo in export

---

backend/src/backup_worker.ts
backend/src/store.ts
backend/src/types.ts
backend/src/voter_checklist.tsx

Polish backup voter checklist certification page

---

backend/src/backup_worker.ts
backend/src/store.ts
backend/src/voter_checklist.tsx

Closes https://github.com/votingworks/vxpollbook/issues/246
Closes https://github.com/votingworks/vxpollbook/issues/247
Closes https://github.com/votingworks/vxpollbook/issues/248

Backup voter checklist polish

---

frontend/src/machine_locked_screen.tsx

Don't prompt to insert poll worker card to unlock when unconfigured

---

backend/src/app.ts

Fixes https://github.com/votingworks/vxpollbook/issues/245

Change voter history file name to voter_history
