script/src/validate-monorepo/validation/index.ts
We aren't using the tests for now, so it's ok to have an outdated CircleCI config. We'll want to revert this change once we use CI again.
=> Don't validate CircleCI config

backend/src/app.ts, backend/src/check_in_receipt.tsx, backend/src/index.ts, backend/src/server.ts, backend/src/store.ts, backend/src/voter_checklist.tsx, frontend/src/api.ts, frontend/src/error_screen.tsx, frontend/src/poll_worker_screen.tsx, libs/printing/src/printer/supported.ts, libs/printing/supported_printers/citizen_ct_e351_thermal_printer.ppd, libs/printing/supported_printers/configs.json, libs/utils/src/format.ts
Sets up the Citizen thermal receipt printer and integrates it into VxPollbook to print a receipt. Note that you can use the `USE_MOCK_PRINTER` env var to use a mock printer (controlled from the dev dock).
=> Print voter check-in receipt

backend/jest.config.js, backend/package.json, backend/schema.sql, backend/src/app.ts, backend/src/index.ts, backend/src/store.test.ts, backend/src/store.ts, backend/src/types.ts, backend/src/workspace.ts, backend/tsconfig.json, pnpm-lock.yaml
Initial implementation of pollbooks syncing events and applying them to the voter table. This adds:
- Simple election table that stores election configuration for persistence on reboots
- Simple voter table that stores voter information (not check in data) for persistence on reboots
- event_log table that stores events (currently check ins and undo check ins) 
Whenever voter information is fetched all voter-related events (which is currently all events) are fetched from the db and applied, in order, to the voters before they are returned. This is not very efficient and should be optimized down the line. 
Whenever the polling interval on network connection sees a connected pollbook (new or old) we tell that pollbook the list of machines with the last synced event for each machine. The …
=> Initial Implementation of Multi-Node data syncing

script/99-mesh-network.rules, script/avahi-autoipd.service, script/initial_configuration.sh, script/join-mesh-network.service, script/setup_basic_mesh.sh
Makes the following improvements to harden the networking setup:
- Updates the udev rule to trigger the join-mesh-network.service service file so that everything goes through that. The udev rule will trigger it when a new wifi adapter is seen, the service file itself has triggers for machine boot, sleep and suspend resumption. 
- Creates a second service file that keeps running after trigger to manage running avahi-autoipd which assigns an IP address on IPv4 to the mesh network interface. If this occurs in the oneshot script then it will send a stop command to avahi-autoipd and the ip address is removed when the service file completes. If we make the entire mesh network service keep running its hard to make it restart properly. 
- Manually restarts the avahi-autoipd service upon …
=> Improve Networking Setup Scripts

backend/schema.sql, backend/src/app.ts, backend/src/store.test.ts, backend/src/store.ts, backend/src/types.ts, backend/src/vector_clock.test.ts, backend/src/vector_clock.ts
We were essentially already implementing vector clocks in order to determine what events we needed to fetch when updating nodes, this PR formalizes that implementation a bit and uses the vector clocks for ordering events. In order to order events deterministically there needs to be a tie breaker for "concurrent" vector clocks. Consider the following simple example: 
NodeA comes online and checks in Bob, that event has a clock of 1 and the vector {NodeA: 1}
NodeB comes online and checks in Greg (before syncing) that event also has a time of one with the vector: {NodeB: 1} 
How do we determine which happened first? Well it doesn't really matter so we break the tie by defaulting to sorting on machineId. If NodeB had synced with NodeA before the check in the vector would look like {NodeA: 1, …
=> Order events with distributed vector clocks

backend/src/store.ts, frontend/src/api.ts
Two small tweaks
- Adds a refetch interval for the get check in count query (cc @jonahkagan ) so that that auto-updates
- Changes the way concurrent vector clocks are tiebroken for ordering event to fallback to system timestamp instead of machine ID. I realized this is better for the following scenario:
Machine A goes offline: While offline it checks in Joe and then undoes that checkin
Machine B: Checks in Joe , several real time minutes later
When Machine A comes back online we want to try to ensure that the undo is ordered before the check in from Machine B. Since the machines were not connected when this all happeend the vector clocks will be concurrent, obviously system time could be wrong here and there is no way to ever completely guarantee we always properly order everything but I …
=> refetch counts and tiebreak clocks by timestamp

backend/package.json, backend/scripts/simulate-check-ins, backend/scripts/simulate_check_ins.ts, backend/src/app.ts, backend/src/store.ts, backend/src/types.ts, frontend/src/nav_screen.tsx, frontend/src/types.ts, pnpm-lock.yaml
Simulation script can be run with ./script/simulate-check-ins from vxpollbook/backend. 
It has a few optional arguments:
-l or --limit to specify a limit on the number of voters to check in
--slow will go in a more "real world" speed sleeping for a random amount of time between 4 and 8 seconds between each check in, if omitted check ins happen as fast as possible
--range or -r to specify a range of first letters for the last name to start with, i.e.  -r A-D will make the script only check in voters with last names starting with A-D. 
I find it useful to run different machines in --slow mode with different ranges so that you can more easily see what events you have from what machines. And make sure there are certain sets of voters that will not be auto checked in if you want to add in …
=> Build out simulation script a bit more

backend/src/app.ts, backend/src/avahi.ts, backend/src/index.ts, backend/src/networking.ts, frontend/src/api.ts, frontend/src/nav_screen.tsx, libs/ui/src/icons.tsx, script/setup_basic_mesh.sh
Updates the setup_basic_mesh.sh script that is run on boot/sleep awakening/etc. to just delete the mesh0 interface if it already exists as a first step. This seems to work more reliably then trying to bring it back up if it gets in any number of broken states. Also adds a UI option (somewhat ugly for now) to force this script to be run to reset the network. Along with some refactoring / new debugging lines / etc. in the networking code.
=> Add networking reset fallback

backend/src/store.ts, frontend/src/shared_components.tsx
When we started caching voters by ID, we lost the implicit ordering that voter search and the backup checklist relied on.
(This PR also adds a file I forgot to commit in #97)
=> Sort voters by name

backend/src/globals.ts, frontend/src/nav_screen.tsx
Always expose network reset option, and update timeout for other pollbooks to 10seconds before showing as not connected.
=> Always show reset button, timeout after 10s

backend/src/check_in_receipt.tsx, backend/src/types.ts, backend/src/voter_checklist.tsx, frontend/src/voter_confirm_screen.tsx
Closes #78 
Removes CVA as an identification method option.
Also changes the confirm check-in screen to always show form elements for photo ID/personal recognizance to avoid having things jump around when you switch methods.
https://github.com/user-attachments/assets/1fe7dcbb-80eb-4379-bd59-3126729975be
=> Remove CVA voter identification method

backend/src/check_in_receipt.tsx, backend/src/store_multi_node.test.ts, backend/src/types.ts, backend/src/voter_checklist.tsx, frontend/src/voter_confirm_screen.tsx
Closes #79 , closes #95 
Adds a field to the check-in flow to record the initials of the recognizer for the personal recognizance identification method. Also puts these initials in the backup voter checklist (and moves them to the initial column of the checklist).
https://github.com/user-attachments/assets/5ffcf718-865f-4392-aa9d-8798d657515e
=> Add field to record initials for personal recognizance 

libs/printing/src/printer/printer.ts
Avoids an issue where, after each print, the printer shows as disconnected because the CUPS server temporarily does not see the printer. While we're not sure of the underlying cause, it seems difficult to debug at this point because we've previously decided options other than `lpinfo` for getting printer connection are worse. For now, just institute a 2 second grace period after every print. Tested on hardware.
=> fix print blip

backend/package.json, backend/src/backup_worker.ts, backend/src/store_multi_node.test.ts, backend/src/voter_checklist.tsx, pnpm-lock.yaml
Closes #107 , fixes #120 
Renders the checklist for each letter of the alphabet separately (with its own header and page count), then concatenates A-K and L-Z into two printable PDFs before exporting to the USB drive.
=> Split backup voter checklist into two PDFs for printing 

libs/printing/src/printer/printer.ts
When printing about 1,000 receipts, I saw one instance of the printer blip still after #111. Upping the timeout slightly.
=> bump grace period

libs/dev-dock/frontend/src/dev_dock.tsx
@jonahkagan feel free to have a better solution here but the dev dock handle is blocking the network indicator on vx dev machines right now so I'm just bumping the arrow handle to the left some to make it more out of the way
=> move dev dock handle to left to not block network indicator

script/avahi-autoipd.action, script/configure-iptables.sh, script/initial_configuration.sh, script/mesh-ipsec.conf, script/update-ipsec.sh, script/update-vxpollbook.sh
This updates the configuration script so that ipsec is automatically configured to encrypt traffic in the 169.254 subnet which we are using to assign IP addresses in using avahi-autoipd. Tested by running on multiple laptops and seeing them still able to connect to one another while tcpdump shows encrypted traffic, sudo ipsec statusall shows an established communication channel, and another laptop, not configured with ipsec on the same mesh network is not able to connect. 
Also adds a script to configure firewall rules so that things are more locked down around that encrypted subnet. Tested manually on laptops but its a little annoying to figure out how to turn off the rules and turn them back on properly so for the purposes of VxDev usage this is not incorporated into the configuration …
=> Configure IPSec and Firewall rules 

frontend/src/api.ts
This solves the flickering that was happening when you search for a voter after checking them in (where it showed the un-checked-in status for a moment)
=> Reset cached voter search after check-ins

backend/schema.sql, backend/src/app.ts, backend/src/backup_worker.ts, backend/src/event_helpers.ts, backend/src/receipts/address_change_receipt.tsx, backend/src/receipts/check_in_receipt.tsx, backend/src/receipts/name_change_receipt.tsx, backend/src/receipts/receipt_helpers.tsx, backend/src/receipts/registration_receipt.tsx, backend/src/receipts/undo_check_in_receipt.tsx, backend/src/store.ts, backend/src/test_helpers.ts, backend/src/types.ts, backend/src/voter_checklist.tsx, libs/ui/src/icons.tsx
Closes #172 
Adds a global receipt number to the bottom of all receipts and prints the last receipt number on the backup voter checklist.
=> Receipt numbers

backend/src/app.ts, backend/src/receipts/address_change_receipt.tsx, backend/src/receipts/check_in_receipt.tsx, backend/src/receipts/name_change_receipt.tsx, backend/src/receipts/receipt_helpers.tsx, backend/src/receipts/registration_receipt.tsx, backend/src/receipts/undo_check_in_receipt.tsx, backend/src/store.ts, frontend/src/election_manager_screen.tsx
Closes #175 
Note that with a shorter election title it should all fit on two lines, which is why I used this layout (to try to save vertical space as much as possible in the average case)
=> Add election title and date to receipt footer

backend/src/receipts/address_change_receipt.tsx, backend/src/receipts/receipt_helpers.tsx
Closes #178 
After a voter's address is changed, use that new address on all receipts.
=> Use changed address on receipts

backend/src/store.ts
Closes #199 
If there's a duplicate receipt number (because two pollbooks produce a receipt without seeing each others' events), this will increment the receipt number by 2, skipping one receipt number.
=> Use current event count as receipt number

backend/src/voter_checklist.tsx, libs/ui/src/icons.tsx
Closes https://github.com/votingworks/vxpollbook/issues/194
Closes https://github.com/votingworks/vxpollbook/issues/195
- Lighten red colored text (to better differentiate it)
- Lighten gray row striping (to save toner)
- Use checkbox icon and increase size
=> Polish backup voter checklist

backend/src/types.ts
Closes #230 
The latest street info file only has a limited number of headers, which is fine because there were a bunch of extra ones that we don't use. This removes them from the type definition just to be safe.
=> Remove unused street info fields from type
